In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Verzeo ML Feb Batch/tissue.csv')

In [4]:
df

x1  x2     y
0   7   7   bad
1   7   4   bad
2   3   4  good
3   1   4  good

In [6]:
#creating input and output i.e. divide data into x and y

In [43]:
x = df.iloc[:, 0:2].values

reshape is to convert to 2d

In [44]:
y = df.iloc[:,2].values.reshape(-1,1)

In [45]:
y

array([['bad'],
       ['bad'],
       ['good'],
       ['good']], dtype=object)

In [46]:
#label encoder (first value becomes 0; the other is 1)
#(can use dummy variables also)

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
le = LabelEncoder()

In [49]:
y = le.fit_transform(y)#convert y to label encoder

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [50]:
y

array([0, 0, 1, 1])

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
classifier = KNeighborsClassifier(n_neighbors=3, metric = 'euclidean')

In [53]:
 #training 

In [54]:
x

array([[7, 7],
       [7, 4],
       [3, 4],
       [1, 4]])

In [55]:
y

array([0, 0, 1, 1])

In [56]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [57]:
pred_y = classifier.predict(x)

In [58]:
pred_y

array([0, 0, 1, 1])

In [35]:
y

array([0, 0, 1, 1])

In [59]:
classifier.predict([[3,7]])

array([1])