In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Verzeo ML Feb Batch/Salary_Data.csv')

In [3]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [8]:
x = df.iloc[:,0].values.reshape(-1,1)

In [9]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [10]:
y = df.iloc[:,1].values.reshape(-1,1)

In [11]:
y

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 93940.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [12]:
#divide x and y for training and testing

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
train_x,test_x,train_y,test_y =train_test_split(x,y,test_size=0.2,random_state =0)#20% testing random state to maintain same values as sir(can give any matching no in a team)

x is splitted in variables train_x and test_x and same for y

In [33]:
test_x

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7]])

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
Lin = LinearRegression()# bring class in a variable to work with it

In [36]:
Lin.fit(train_x,train_y)#training model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
pred_y = Lin.predict(test_x)

In [38]:
pred_y

array([[ 40748.96184072],
       [122699.62295594],
       [ 64961.65717022],
       [ 63099.14214487],
       [115249.56285456],
       [107799.50275317]])

In [39]:
test_y

array([[ 37731.],
       [122391.],
       [ 57081.],
       [ 63218.],
       [116969.],
       [109431.]])

In [40]:
np.concatenate((test_y,pred_y), axis= 1)#comparing orginal o/p from dataset thats given with our machine produced o/p,,, axis=1 is for rows axis=0 is one after the other

array([[ 37731.        ,  40748.96184072],
       [122391.        , 122699.62295594],
       [ 57081.        ,  64961.65717022],
       [ 63218.        ,  63099.14214487],
       [116969.        , 115249.56285456],
       [109431.        , 107799.50275317]])

to calculate error

In [41]:
test_y - pred_y

array([[-3017.96184072],
       [ -308.62295594],
       [-7880.65717022],
       [  118.85785513],
       [ 1719.43714544],
       [ 1631.49724683]])

taking absolute mean error

In [42]:
np.abs(test_y - pred_y)

array([[3017.96184072],
       [ 308.62295594],
       [7880.65717022],
       [ 118.85785513],
       [1719.43714544],
       [1631.49724683]])

In [43]:
np.abs(test_y - pred_y).mean()#mean abs error

2446.1723690465055

In [45]:
Lin.predict([[3.5]])#yrs of exp thats not in the dataset

array([[59374.11209418]])

the salary will be +/- error that is 2446.

In [27]:
#to find square error and abs error through lib

In [29]:
from sklearn import metrics

In [46]:
metrics.mean_absolute_error(test_y, pred_y)

2446.1723690465055

In [47]:
metrics.mean_squared_error(test_y,pred_y)

12823412.298126549

### **The end of lecture 5//**