lgr is used when data cannot be separated by a linear line

supvervised learning - classification algorithm that uses probability to classify

y = (x-x')(y-y')/(x-x')^2 = log(p)/(1-p) 

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Verzeo ML Feb Batch/Loan_logistic.csv')

In [ ]:
df

gender married   ch  income  loanamt status
0      Male      No  1.0    5849      NaN      Y
1      Male     Yes  1.0    4583    128.0      N
2      Male     Yes  1.0    3000     66.0      Y
3      Male     Yes  1.0    2583    120.0      Y
4      Male      No  1.0    6000    141.0      Y
..      ...     ...  ...     ...      ...    ...
609  Female      No  1.0    2900     71.0      Y
610    Male     Yes  1.0    4106     40.0      Y
611    Male     Yes  1.0    8072    253.0      Y
612    Male     Yes  1.0    7583    187.0      Y
613  Female      No  0.0    4583    133.0      N

[614 rows x 6 columns]

In [ ]:
df.isnull()#asking if a value is null or not

gender  married     ch  income  loanamt  status
0     False    False  False   False     True   False
1     False    False  False   False    False   False
2     False    False  False   False    False   False
3     False    False  False   False    False   False
4     False    False  False   False    False   False
..      ...      ...    ...     ...      ...     ...
609   False    False  False   False    False   False
610   False    False  False   False    False   False
611   False    False  False   False    False   False
612   False    False  False   False    False   False
613   False    False  False   False    False   False

[614 rows x 6 columns]

In [ ]:
df.isnull().sum()#to calculate the total missing values

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [ ]:
df.dropna(inplace=True)#changes original df#drops nullvalues

In [ ]:
df.isnull().sum()

gender     0
married    0
ch         0
income     0
loanamt    0
status     0
dtype: int64

In [ ]:
df.drop(columns='gender', inplace=True)

In [ ]:
df

married   ch  income  loanamt status
1       Yes  1.0    4583    128.0      N
2       Yes  1.0    3000     66.0      Y
3       Yes  1.0    2583    120.0      Y
4        No  1.0    6000    141.0      Y
5       Yes  1.0    5417    267.0      Y
..      ...  ...     ...      ...    ...
609      No  1.0    2900     71.0      Y
610     Yes  1.0    4106     40.0      Y
611     Yes  1.0    8072    253.0      Y
612     Yes  1.0    7583    187.0      Y
613      No  0.0    4583    133.0      N

[529 rows x 5 columns]

In [ ]:
df.dtypes

married     object
ch         float64
income       int64
loanamt    float64
status      object
dtype: object

In [1]:
#dummy variables

In [ ]:
df = pd.get_dummies(df, drop_first=True )#converting objects to 1 and 0's

In [ ]:
df

ch  income  loanamt  married_Yes  status_Y
1    1.0    4583    128.0            1         0
2    1.0    3000     66.0            1         1
3    1.0    2583    120.0            1         1
4    1.0    6000    141.0            0         1
5    1.0    5417    267.0            1         1
..   ...     ...      ...          ...       ...
609  1.0    2900     71.0            0         1
610  1.0    4106     40.0            1         1
611  1.0    8072    253.0            1         1
612  1.0    7583    187.0            1         1
613  0.0    4583    133.0            0         0

[529 rows x 5 columns]

In [ ]:
import numpy as np

In [ ]:
y = df['status_Y'].values

In [ ]:
x = df.drop(columns='status_Y').values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test,y_train,y_test=train_test_split(x,y, test_size =0.2, random_state= 0)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=uint8)

In [ ]:
y_test

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=uint8)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(y_test,y_pred)

In [ ]:
cm

array([[16, 17],
       [ 3, 70]])

In [ ]:
score=lr.score(x_test,y_test)

In [ ]:
score

0.8113207547169812

In [ ]:
lr.predict([[1.0,4590,100,1]])

array([1], dtype=uint8)